#pragma once

#ifdef __cplusplus
extern "C" {
#endif

enum {
    ICVBASE_GENERAL_ERROR = -1,
    ICVBASE_NO_ERROR = 0,
    ICVBASE_INIT_ERROR,
    ICVBASE_REGISTER_ERROR,
    ICVBASE_INSTANCE_ERROR,
    ICVBASE_INPUT_ERROR,
    ICVBASE_SHAPE_ERROR,
    ICVBASE_SUPPORT_ERROR,
    ICVBASE_MEMORY_ERROR,
    ICVBASE_FILE_OPERATION_ERROR,
    ICVBASE_NETWORK_ERROR,
    ICVBASE_ALGORITHM_EXECUTION_ERROR,
    ICVBASE_CONFIGURATION_ERROR,
    ICVBASE_EXTERNAL_DEPENDENCY_ERROR,
    ICVBASE_CONCURRENCY_ERROR,
    ICVBASE_PERMISSION_ERROR,
    ICVBASE_IO_ERROR,
    ICVBASE_UNKNOWN_ERROR
};

#ifdef __cplusplus
};
#endif