#pragma once

#ifdef __cplusplus
extern "C" {
#endif

enum {
    ICVBASE_GENERAL_ERROR = -1,
    ICVBASE_NO_ERROR = 0,
    ICVBASE_INIT_ERROR = 1,
    ICVBASE_REGISTER_ERROR = 2,
    ICVBASE_INSTANCE_ERROR = 3,
    ICVBASE_INPUT_ERROR = 4,
    ICVBASE_SHAPE_ERROR = 5,
    ICVBASE_SUPPORT_ERROR = 6,
    ICVBASE_MEMORY_ERROR = 7,
    ICVBASE_FILE_OPERATION_ERROR = 8,
    ICVBASE_NETWORK_ERROR = 9,
    ICVBASE_ALGORITHM_EXECUTION_ERROR = 10,
    ICVBASE_CONFIGURATION_ERROR = 11,
    ICVBASE_EXTERNAL_DEPENDENCY_ERROR = 12,
    ICVBASE_CONCURRENCY_ERROR = 13,
    ICVBASE_PERMISSION_ERROR = 14,
    ICVBASE_IO_ERROR = 15,
    ICVBASE_UNKNOWN_ERROR = 16
};

#ifdef __cplusplus
};
#endif