// 定义默认配置
// 格式DEFINE_DEFAULT_CONFIG(Type, Section, Key, DefaultValue)
DEFINE_DEFAULT_CONFIG_ITEM(int, iCVFaceDetect, None, 0)
DEFINE_DEFAULT_CONFIG_ITEM(int, iCVFaceDetect, min_face_size_h_thres, 30)
DEFINE_DEFAULT_CONFIG_ITEM(int, iCVFaceDetect, min_face_size_w_thres, 30)
DEFINE_DEFAULT_CONFIG_ITEM(float, iCVFaceDetect, detect_thres, 0.5f)
DEFINE_DEFAULT_CONFIG_ITEM(bool, iCVFaceDetect, use_crude, false)
DEFINE_DEFAULT_CONFIG_ITEM(int, iCVFaceDetect, bytetrack_track_buffer, 30)
DEFINE_DEFAULT_CONFIG_ITEM(float, iCVFaceDetect, bytetrack_track_thresh, 0.5)
DEFINE_DEFAULT_CONFIG_ITEM(float, iCVFaceDetect, bytetrack_high_thresh, 0.6)
DEFINE_DEFAULT_CONFIG_ITEM(int, iCVFaceDetect, model_input_h, 160)
DEFINE_DEFAULT_CONFIG_ITEM(int, iCVFaceDetect, model_input_w, 160)
DEFINE_DEFAULT_CONFIG_ITEM(float, iCVFaceDetect, nms_iou_thres, 0.3f)
DEFINE_DEFAULT_CONFIG_ITEM(int, iCVFaceDetect, max_init_nms_rect_cnt, 1000)
DEFINE_DEFAULT_CONFIG_ITEM(int, iCVFaceDetect, Count, 0)