#include "ort_wrapper.h"
namespace DNN_WRAPPER {
const std::unordered_map<RESTYPE, const std::string>
    ORTWrapper::restype_name_map_ = {
        {RESTYPE_FACE_DETECT_CPU, "RESTYPE_FACE_DETECT_CPU"},
        {RESTYPE_FACE_DETECT_NPU, "RESTYPE_FACE_DETECT_NPU"},
        {RESTYPE_FACE_ALIGNMENT_CPU, "RESTYPE_FACE_ALIGNMENT_CPU"},
        {RESTYPE_FACE_ALIGNMENT_NPU, "RESTYPE_FACE_ALIGNMENT_NPU"},
        {MODTYPE_FACE_SINGLETRACK_CPU, "MODTYPE_FACE_SINGLETRACK_CPU"},
        {MODTYPE_FACE_SINGLETRACK_NPU, "MODTYPE_FACE_SINGLETRACK_NPU"}};

const std::unordered_map<RESTYPE, std::vector<RESTYPE>>
    ORTWrapper::modtype_restypes_map_ = {
        {MODTYPE_FACE_SINGLETRACK_CPU,
         {RESTYPE_FACE_DETECT_CPU, RESTYPE_FACE_ALIGNMENT_CPU}},
        {MODTYPE_FACE_SINGLETRACK_NPU,
         {RESTYPE_FACE_DETECT_NPU, RESTYPE_FACE_ALIGNMENT_NPU}}};

} // namespace DNN_WRAPPER